package com.example.Testshop.enums;

public enum AdminStep {
    MENU, LOGIN,
    MAIN_MENU, GOODS_MENU,
    SELLERS_MENU, ADD_PRODUCT,
    EDIT_PRODUCT, DELETE_PRODUCT,
    GET_PRODUCT, ADD_SELLER,
    DELETE_SELLER,RESTART_PASSWORD,
    BONUS_PRODUCT,ADD_BONUS, DELETE_BONUS, BONUS_CREATE
}
